name: ATLAS

services:
  atlas:
    build:
      context: .
    depends_on:
      - postgres
      - minio
      - grafana
    environment:
      OTEL_SERVICE_NAME: atlas
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana:4317
    profiles:
      - atlas
    ports:
      - "8000:8000"
    volumes:
      - ./settings.localdev.toml:/config/settings.toml

  grafana:
    image: grafana/otel-lgtm@sha256:9f7d636403222fd38ffb804b1b35da97b2c620ff873d331ce72e9f9faaa4547d
    init: true
    restart: always
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

  postgres:
    image: postgres:latest@sha256:29e0bb09c8e7e7fc265ea9f4367de9622e55bae6b0b97e7cce740c2d63c2ebc0
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:latest@sha256:451fe6858cb770cc9d0e77ba811ce287420f781c7c1b806a386f6896471a349c
    environment:
      - MINIO_FORCE_NEW_KEYS=yes
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DEFAULT_BUCKETS=atlas
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/bitnami/minio/data

volumes:
  postgres-data:
  minio-data:
  tempo-data:
