name: ATLAS

services:
  atlas:
    build:
      context: ./backend/
    depends_on:
      - postgres
      - minio
      - grafana
    environment:
      OTEL_SERVICE_NAME: atlas
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana:4317
    profiles:
      - atlas
    ports:
      - "8000:8000"
    volumes:
      - ./backend/settings.localdev.toml:/config/settings.toml

  grafana:
    image: grafana/otel-lgtm
    restart: always
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:latest
    environment:
      - MINIO_FORCE_NEW_KEYS=yes
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DEFAULT_BUCKETS=atlas
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/bitnami/minio/data

volumes:
  postgres-data:
  minio-data:
  tempo-data:
