name: ATLAS

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:latest
    environment:
      - MINIO_FORCE_NEW_KEYS=yes
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniosecret
      - MINIO_DEFAULT_BUCKETS=atlas
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/bitnami/minio/data

volumes:
  postgres-data:
  minio-data:
