from datetime import datetime
from typing import TYPE_CHECKING, Any

from pydantic import computed_field
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, Identity, Relationship, SQLModel

if TYPE_CHECKING:
    from .stack import Stack


class RoomBase(SQLModel):
    """Shared properties"""

    title: str = Field(min_length=1, max_length=255)
    annotations: dict[str, Any] = Field({}, nullable=False, sa_type=JSONB)


class RoomCreate(RoomBase):
    """Properties to receive on room creation"""

    pass


class RoomUpdate(RoomBase):
    """Properties to receive on room update"""

    title: str | None = None  # type: ignore
    annotations: dict[str, Any] | None = None  # type: ignore


class Room(RoomBase, table=True):
    """Database model, database table inferred from class name"""

    id: int | None = Field(default=None, primary_key=True, sa_column_args=[Identity(always=True)])
    """id will be generated by the database"""
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)

    stacks: list["Stack"] = Relationship(back_populates="room", cascade_delete=False)

    @computed_field
    def stack_count(self) -> int:
        """Total number of stacks in this room"""
        return len(self.stacks)


class RoomPublic(RoomBase):
    """Properties to return via API, id is always required"""

    id: int
    created_at: datetime
    updated_at: datetime
