from datetime import datetime
from typing import TYPE_CHECKING, Any

from pydantic import computed_field
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Column, DateTime, Field, Identity, Relationship, SQLModel, func

if TYPE_CHECKING:
    from .stack import Stack


class RoomBase(SQLModel):
    """Shared properties"""

    title: str = Field(min_length=1, max_length=255)
    annotations: dict[str, Any] = Field({}, nullable=False, sa_type=JSONB)


class RoomCreate(RoomBase):
    """Properties to receive on room creation"""

    pass


class RoomUpdate(RoomBase):
    """Properties to receive on room update"""

    title: str | None = None  # type: ignore
    annotations: dict[str, Any] | None = None  # type: ignore


class Room(RoomBase, table=True):
    """Database model, database table inferred from class name"""

    id: int | None = Field(default=None, primary_key=True, sa_column_args=[Identity(always=True)])
    """id will be generated by the database"""
    created_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), nullable=False),
    )
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), onupdate=func.now()),
    )

    stacks: list["Stack"] = Relationship(
        back_populates="room",
        cascade_delete=False,
        sa_relationship_kwargs={"lazy": "selectin"},
    )

    @computed_field
    def stack_count(self) -> int:
        """Total number of stacks in this room"""
        return len(self.stacks)


class RoomPublic(RoomBase):
    """Properties to return via API, id is always required"""

    id: int
    created_at: datetime
    updated_at: datetime | None
