"""item_tag_unique

Revision ID: 27fb1edf4b8e
Revises: 78f806edc6f5
Create Date: 2025-03-24 09:49:53.917953

"""
# mypy: disallow_untyped_calls=False

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '27fb1edf4b8e'
down_revision: Union[str, None] = '78f806edc6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_item_tag', 'itemtaglink', ['item_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_item_tag', 'itemtaglink', type_='unique')
    # ### end Alembic commands ###
