from datetime import datetime
from typing import TYPE_CHECKING, Any

from pydantic import computed_field
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Column, DateTime, Field, Identity, Relationship, SQLModel, func

from .room import Room

if TYPE_CHECKING:
    from .item import Item


class StackBase(SQLModel):
    """Shared properties"""

    title: str = Field(min_length=1, max_length=255)
    room_id: int | None = Field(default=None, foreign_key="room.id", ondelete="SET NULL")
    annotations: dict[str, Any] = Field({}, nullable=False, sa_type=JSONB)


class StackCreate(StackBase):
    """Properties to receive on stack creation"""

    pass


class StackUpdate(StackBase):
    """Properties to receive on stack update"""

    title: str | None = None  # type: ignore
    annotations: dict[str, Any] | None = None  # type: ignore


class Stack(StackBase, table=True):
    """Database model, database table inferred from class name"""

    id: int | None = Field(default=None, primary_key=True, sa_column_args=[Identity(always=True)])
    """id will be generated by the database"""
    created_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), server_default=func.now(), nullable=False),
    )
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(DateTime(timezone=True), onupdate=func.now()),
    )

    room: Room | None = Relationship(
        back_populates="stacks",
        sa_relationship_kwargs={"lazy": "selectin"},
    )
    items: list["Item"] = Relationship(
        back_populates="stack",
        cascade_delete=False,
        sa_relationship_kwargs={"lazy": "selectin"},
    )

    @computed_field
    def item_count(self) -> int:
        """Total number of items in this stack"""
        return len(self.items)


class StackPublic(StackBase):
    """Properties to return via API, id is always required"""

    id: int
    created_at: datetime
    updated_at: datetime | None
